### ISSUE TITLE
Dependency on Flask < 2.0.0

### ISSUE THREAD

**Issue by KMDEVAIAH** [antarctica/flask-azure-oauth#16]
Any plans for supporting latest versions of Flask?

**Comment by jgwinner** [comment]
I had the same qustion also, was quite surprised when pip downgraded my Flask

**Comment by RRGTHWAR** [comment]
While we're waiting for a release that officially supports Flask 2.x, I've found flask_azure_oauth works fine with 2.x. This obviously isn't ideal, but if you go into your site packages and open flask_azure_oauth-0.5.0.dist-info/METADATA and delete the "<2.0.0" in line 18, you can upgrade Flask and everything works.

**Comment by felnne** [comment]
Hi,

Thank for you raising this, and apologies for the delayed response. I have now updated this package generally, including adding Flask 2.0 support.

See https://pypi.org/project/flask-azure-oauth/0.6.0/ for the latest version which should hopefully resolve this issue.
