### ISSUE TITLE
Required custom claim `azp`

### ISSUE THREAD

**Issue by SudhindraKovalam** [antarctica/flask-azure-oauth#2]
When used, I notice that a custom claim `azp` is set as a required claim.
In order to make this module generic, IMO this dependency should be removed.

Also, I would like to understand the rationale behind it?
Perhap accept any desired custom claims as an optional parameter in the `ctor`

**Comment by felnne** [comment]
Hi @SudhindraKovalam,

This package targets the Microsoft Identity Platform and more specifically its OAuth support, it doesn't seek to validate OAuth tokens generically.

In Microsoft's implementation, the `azp` claim will always be included, in case protected resources want to whitelist specific client applications. As the claim is always included I've made it required.

Is there a reason you need this claim to be optional?

**Comment by SudhindraKovalam** [comment]
I see the issue. Makes sense. My suggestion would be expose the options object. so, if the user wants to change certain claims, it would allow it.
