### ISSUE TITLE
Package can't be installed in older Python versions

### ISSUE THREAD

**Issue by felnne** [antarctica/flask-azure-oauth#3]
See https://github.com/antarctica/flask-azure-oauth/pull/1#issuecomment-631376550 for context.

**Comment by felnne** [comment]
Hi @Laksh05,

In relation to you not being able to install this package using Python 3.7, I think I've fixed this in a new 0.4.1 release:

https://github.com/antarctica/flask-azure-oauth/blob/v0.4.1/CHANGELOG.md#041---2020-05-23

**Comment by Laksh05** [comment]
Hi @felnne 
Thanks a lot😊 Will install new version.

Thank you.

**Comment by felnne** [comment]
@Laksh05 - did this work for you in the end?

**Comment by Laksh05** [comment]
Hi @felnne ,
Sorry. Yes its working. Thank you :)
