### ISSUE TITLE
401 after long uptime

### ISSUE THREAD

**Issue by krisnashaypp** [antarctica/flask-azure-oauth#33]
Hi! Thank you for this nice and easy to use package. I have a flask API that runs 24/7 and now twice I've encountered and error that when the API has been up for more than 2 weeks or so I start getting 401 when calling it from my client application, a quick restart of the backend solves this issue.

I guess there's some kind of caching of the azure data going on that never refreshes but I'm not sure. I don't see anything about this in the docs so I'm grateful for any suggestions. 

Thanks!

**Comment by felnne** [comment]
I think this is the same as #27 and should now be fixed in v0.8.0.

I realise this has been unanswered for a while though so you've likely looked at another solution.

If not and this is still a problem let me know and I'm happy to take a look.
