### ISSUE TITLE
Support for China Azure AAD Endpoint

### ISSUE THREAD

**Issue by nonokangwei** [antarctica/flask-azure-oauth#6]
Need support endpoint parameter to supprot Azure China AAD Endpoint.

**Comment by felnne** [comment]
Hi @nonokangwei,

Whilst I can see this would be useful to others, I won't have any time available to add this as it's of limited use to my organisation.

I'm happy to review a pull request from yourself or others to add this depending on what changes are required however.

Thanks,
Felix.
