### ISSUE TITLE
Support for OAUTH v1.0 tokens

### ISSUE THREAD

**Issue by r1v3n** [antarctica/flask-azure-oauth#7]
Currently the lib only support OATH v2.0 tokens. The 'azp' claim from Azure AD is required from the token (only present in 2.0). It would be useful to be able to use v1.0 tokens without that claim.

**Comment by felnne** [comment]
Hi @r1v3n,

Sorry for the delay in replying, I'm working on the next release of this package and support for v1.0 tokens should now be added.

I've made a test build that adds support for that (along with other changes) here: 

https://test.pypi.org/project/flask-azure-oauth/0.4.1.post17.dev0/

Before I make this a real release could you check this does what you need?

A full list of changes in the upcoming version is available here:

https://github.com/antarctica/flask-azure-oauth/blob/master/CHANGELOG.md#unreleased

**Comment by felnne** [comment]
The release containing support for V1 tokens is now published and should resolve this issue. Please re-open if it does not.

https://pypi.org/project/flask-azure-oauth/0.5.0/
