### ISSUE TITLE
Does not support custom signing keys as a result of using the claims-mapping feature

### ISSUE THREAD

**Issue by louisliu15** [antarctica/flask-azure-oauth#8]
According to AD doc: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-the-signature
> If your app has custom signing keys as a result of using the claims-mapping feature, you must append an appid query parameter containing the app ID to get a jwks_uri pointing to your app's signing key information, which should be used for validation. For example: https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration?appid=6731de76-14a6-49ae-97bc-6eba6914391e contains a jwks_uri of https://login.microsoftonline.com/{tenant}/discovery/keys?appid=6731de76-14a6-49ae-97bc-6eba6914391e.

My AD application uses a custom signin key which is not shown in the public key dictionary. So I can't get my token signed with the public AD keys.

**Comment by felnne** [comment]
Hi @louisliu15,

Thanks for reporting this, I didn't know about that feature, it sounds interesting.

For supporting it, I've a few ideas that vary in effort but that would allow greater flexibility:

1. add the `appid` parameter automatically
2. allow the JWKS URI to set (as `AZURE_OAUTH_JWKS_URI` or similar)
3. use the `opened-configuration` endpoint to determine which JWKS URI to use

Option 1 would be the least change to the library, as assuming the `appid` query parameter value is the same as the `AZURE_OAUTH_APPLICATION_ID` value that this library uses, then it's already known. I assume that it's fine to use this for applications that don't use the custom signing feature. I checked with one of my applications and it returned a subset of key set returned without (i.e. normally the JWKS returns 2 keys, with the appid appended it returned only the 1st of those).

Option 2 would more flexible but increase the information the user needs to provide, though not by much.

Option 3 would be the most flexible and dynamic, we could use it to get the JWKS URI but also the Issuer URI (which is used elsewhere). I'm guessing it would also add support for things like regional clouds and may be useful for future things that might be included in that config. It's also clearly the intended way of getting these values. It is also the most work however.

Personally I like the idea of option 3, as I think it would fix this most properly. It would mean the user adding a new `AZURE_OAUTH_WELL_KNOWN_CONFIG_URI` option and removing the `AZURE_OAUTH_TENANCY` option but I don't think that would be a big problem.

Presumably option 3 would add the flexibility you need? If so now is a good time as I'm going to be working on this again very soon (hopefully starting tomorrow).

**Comment by louisliu15** [comment]
After investigating deeper on the Azure JWKS_URI, I found that https://login.microsoftonline.com/{tenant_id}/v2.0/discovery/v2.0/keys?appid={application_id} will always return the signing key that matches, no matter the AD application uses public or custom key. So I think it will be more concise to always attach the application id into the JWKS_URI.
Here is the reference I think can be useful: [AzureAD Open ID configuration documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#sample-response)

**Comment by felnne** [comment]
Hi @louisliu15,

Ah ok, in that case option 1 would presumably be enough?

If so I've made a test build that adds support for that (along with other changes) here: 

https://test.pypi.org/project/flask-azure-oauth/0.4.1.post17.dev0/

Before I make this a real release could you check this does what you need?

A full list of changes in the upcoming version is available here:

https://github.com/antarctica/flask-azure-oauth/blob/master/CHANGELOG.md#unreleased

**Comment by louisliu15** [comment]
Hi @felnne 

I installed the unreleased build in my demo and it worked perfectly fine for me. Thanks for the effort.

**Comment by felnne** [comment]
@louisliu15 

Great, thanks for confirming - I've fixed some issues for others too so I'll wait a bit to check they work for them before making this a proper release.

**Comment by felnne** [comment]
@louisliu15 for reference the 0.5.0 release is now published - https://pypi.org/project/flask-azure-oauth/0.5.0/
