### ISSUE TITLE
[Question] Reading basic information of the access token

### ISSUE THREAD

**Issue by janusch** [antarctica/flask-azure-oauth#9]
Is it possible to read information from the access token?
I am using the auth decorator to protect my routes. Would it be possible to make the contents of the token available in the route method?
I would like to be able to use the username in the route in a db query within the protected route.
Maybe this is already possible. Could you give me an example using the decoded token information in the protected route?

Another issue that I have not figured out is if it is possible to use the same application id for both the `AZURE_OAUTH_APPLICATION_ID` and `AZURE_OAUTH_CLIENT_APPLICATION_IDS`? Maybe you have a short answer to that?

Thank you again for creating and maintaining this package and for the great documentation on how to use azure oauth!

**Comment by felnne** [comment]
Hi @janusch,

> Would it be possible to make the contents of the token available in the route method?

That should be possible through the base AuthLib package, specifically the JWT class [RFC 7519](https://docs.authlib.org/en/latest/specs/rfc7519.html) in that you can do something like:

```python
from authlib.integrations.flask_oauth2 import current_token

# setup app and auth provider etc.

@app.route("/claims")
@app.auth()
def claims():
  return current_token.claims
```

That will return a dict that you can use as needed.

---

> Another issue that I have not figured out is if it is possible to use the same application id for both the `AZURE_OAUTH_APPLICATION_ID` and `AZURE_OAUTH_CLIENT_APPLICATION_IDS`?

I'm not sure about that but off the top of my head I don't think this library would get in the way of doing so - i.e. you can make those variables the same value (with the second as a list of 1) but I don't know how that would within Azure.

Also the upcoming release will remove the need to define `AZURE_OAUTH_CLIENT_APPLICATION_IDS` so if that was a problem it could be avoided from 0.5.0 onwards.

Hope that helps.

**Comment by janusch** [comment]
Hi @felnne 
Thank you for the quick reply!

I could get the user from the claims the way you describe above.

Looking forward to the upcoming release,
Have a great day!
